#!/bin/bash
if [ -f "dir.csv" ]; then
    dir=$(cat dir.csv)
    filename=""$dir"/金沢大学教務システム - 抽選科目登録状況.htm"
else
    filename="$HOME/金沢大学教務システム - 抽選科目登録状況.htm"
fi

cat "$filename" > temp
name=$( cat temp | grep "ctl00_phContents_ucRegistrationStatus_lblDate" | sed 's/[ :\/]//g ; s/<span>//g ; s/<spanid="ctl00_phContents_ucRegistrationStatus_lblDate">//g ; s/\r//g' )

echo -n > trim1
mode=1
while IFS= read -r line; do
    if [[ $line == "						<table"* ]]; then
        mode=2
    elif [[ $line == "						</tbody></table>"* ]]; then
        mode=3
    else
		:
	fi

	if [ $mode = "1" ]; then
		:
	elif [ $mode = "2" ]; then
	    echo "$line" >> trim1
	else
		:
	fi
done < "temp"

cat trim1 | sed -E ':a;N;$!ba;s/\r//g;s/\n//g' > trim2
cat trim2 | sed 's/<\/tr><tr style="background-color:White;">/\n/g ; s/<\/tr><tr style="background-color:#EAF0E0;border-color:#A0A0A0;">/\n/g' > trim3
cat trim3 | sed 's/<td[^>]*>/<td>/g ; s/<span[^>]*>/<span>/g ; s/ //g ; s/<span>//g ; s/<\/span>//g ; s/	//g' > trim4
cat trim4 | sed 's/<\/td><td>/,/g ; s/<td>//g ; s/<\/td>//g ; s/amp;//g ; s/<\/tr>//g' > trim5
echo >> trim5

sed -i -n '2,$p' trim5
echo "時間割番号,科目区分,時間割名,曜日時限,教員名,対象学生,適正人数,全登録数,優先指定,第１希望,第２希望,第３希望,第４希望,第５希望" > "risyu$name.csv"
cat trim5 >> "risyu$name.csv"

rm trim*
rm temp
exit