#!/bin/bash
filename="$HOME/金沢大学教務システム - 抽選科目登録状況.htm"

#cat "$filename" | grep table

echo -n > trim1
mode=1
while IFS= read -r line; do
    if [[ $line == "						<table"* ]]; then
        mode=2
    elif [[ $line == "						</tbody></table>"* ]]; then
        mode=3
    else
		:
	fi

	if [ $mode = "1" ]; then
		:
	elif [ $mode = "2" ]; then
	    echo "$line" >> trim1
	else
		:
	fi
done < "$filename"

cat trim1 | sed -E ':a;N;$!ba;s/\r//g;s/\n//g' > trim2
cat trim2 | sed 's/<\/tr><tr style="background-color:White;">/\n/g' | sed 's/<\/tr><tr style="background-color:#EAF0E0;border-color:#A0A0A0;">/\n/g' > trim3


cat trim3 | sed 's/<td[^>]*>/<td>/g' | sed 's/<span[^>]*>/<span>/g' | sed 's/ //g' | sed 's/<span>//g' | sed 's/<\/span>//g' | sed 's/	//g' > trim4
filename="trim4"

cat trim4 | sed 's/<\/td><td>/,/g' | sed 's/<td>//g' | sed 's/<\/td>//g' | sed 's/amp;//g' > trim5
echo >> trim5

sed -i -n '2,$p' trim5

cat trim5
rm trim*

exit
while IFS= read -r line; do
    mode=1
    for (( i=0; i<${#line}; i++ )); do
        if [ $mode -eq 1 ]; then
            if [ "${line:$i:1}" = ">" ]; then
                mode=2
            fi
        elif [ $mode -eq 2 ]; then
            if [ "${line:$i:1}" = "<" ]; then
                mode=3
            else
                echo -n ${line:$i:1}
            fi
        elif [ $mode -eq 3 ]; then
            if [ "${line:$i:1}" = ">" ]; then
                mode=2
                echo -n ","
            fi
        fi
    done
    echo ""  # To move to the next line for each line in the file
done < "$filename"

exit